services:
  backend:
    build:
      context: ../
      dockerfile: deployments/Dockerfile.dev
    ports:
      - "8080"
    volumes:
      - ../:/app
      - ../database/data:/app/database/data
    env_file:
      - ../.env

  nginx:
    image: nginx:latest
    container_name: hintermann_nginx
    ports:
      - "80:80"
    volumes:
      - ../config/nginx.conf:/etc/nginx/nginx.conf
      - ../:/app
    depends_on:
      - backend
