services:
  app:
    build:
      context: ../
      dockerfile: deployments/Dockerfile.app.dev
    container_name: app
    volumes:
      - ../:/app
    env_file:
      - ../.env

  nginx:
    build:
      context: ../
      dockerfile: deployments/Dockerfile.nginx.dev
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
