FROM golang:1.23.1-bookworm AS builder

WORKDIR /app

COPY . .

COPY go.mod go.sum ./
RUN go mod download

RUN GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o myapp cmd/main.go

FROM gcr.io/distroless/base

WORKDIR /app

COPY --from=builder /app/myapp .
COPY --from=builder /app/database/migrations ./database/migrations
COPY --from=builder /app/internal/views ./internal/views
COPY --from=builder /app/static/pdf ./static/pdf

EXPOSE 8080

CMD ["./myapp"]
