#!/bin/bash

session=$(tmux display-message -p '#S')
original_window=$(tmux display-message -p '#I')

tmux new-window -t "$session:" 

sleep 1

new_window=$(tmux display-message -p '#I')
tmux send-keys -t "$session:$new_window" 'docker-compose -f scripts/docker-compose.yml up' C-m

sleep 5 

tmux select-window -t "$session:$original_window"

tmux send-keys 'cd scripts' C-m
tmux send-keys 'docker-compose exec db mysql -uuser -ppassword database' C-m
